name: Build and push the Docker image to Google Artifact Registry, Deploy it to the GCP VsM

on:
  push:
    branches:
      - main

env:
  GCP_PROJECT_ID: gold-episode-346919
  GCP_ARTIFACT_REGION: us-east4
  ARTIFACT_REPOSITORY: new-musical-app

jobs:
  build-and-deploy:
    name: Build and Push Docker Image to Artifact Registry
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Configure Docker to Authenticate with Artifact Registry
        run: |
          gcloud auth configure-docker $GCP_ARTIFACT_REGION-docker.pkg.dev

      - name: Create .env File
        run: |
          echo "${{ secrets.ENV_FILE_CONTENT }}" > .env

      - name: Build, Tag, and Push Image to Artifact Registry
        run: |
          SERVICE_NAME=$(echo $(basename $GITHUB_REPOSITORY) | tr -cd '[:alnum:]_.-' | awk '{print tolower($0)}')
          BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}" | tr '/' '-' | awk '{print tolower($0)}')
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7 | awk '{print tolower($0)}')
          IMAGE_TAG=${BRANCH_NAME}-${SHORT_SHA}
          DEPLOYMENT_IMAGE=${GCP_ARTIFACT_REGION}-docker.pkg.dev/$GCP_PROJECT_ID/$ARTIFACT_REPOSITORY/${SERVICE_NAME}:${IMAGE_TAG}
          echo "Building and pushing $DEPLOYMENT_IMAGE"
          docker build \
            --build-arg ENV_FILE=.env \
            -t $DEPLOYMENT_IMAGE .

          docker push $DEPLOYMENT_IMAGE
